### PR TITLE
New lab based on [no-ratelimiting-bug]

### PR DESCRIPTION
**Pull request by abhiabhi2306**
- New Lab based on no ratelimiting vulnerability.

### CODE REVIEW

**Comment by blabla1337** [comment]
Thank you very much for your contribution, we really appreciate it!
One small remark, can you also make a write-up using this as a example template:
https://github.com/blabla1337/skf-labs/blob/master/kbid-1-filename-injection.md

Also don't forget to add your write-up in the SUMMARY.md file :)

**Comment by abhiabhi2306** [comment]
Thank you for the response, I was actually working on the writeup, I'll add it in a few minutes.


P.S: I noticed that there are several styling issues on readme file (the one's with the % formatters), do you mind me fixing them?

**Comment by blabla1337** [comment]
Aah super, thanks. No those are intended, we use Gitbook to display the Markdown and write-ups so please leave them :)

You can check them here:
https://owasp-skf.gitbook.io/asvs-write-ups/

**Comment by abhiabhi2306** [comment]
Dear Glenn, 

I've added the writeup just now, 

If you could approve the changes, then i can put the link to the lab's directory on the summary.md file, can you please assign a kbid id also?


Regards, 
Abhi

**Pull request merged**
