### PR TITLE
More shrinking

### PR DESCRIPTION
**Pull request by tsluyter**
Based on the work from pull request 114, I've decided to shrink down a lot more containers. Each drops down from 330MB to about 71MB. That will save our students a lot of storage.

### CODE REVIEW

**Comment by tsluyter** [comment]
Before I continue shrinking other containers, let me know what you think about this new approach.

**Comment by tsluyter** [comment]
I'm changing the order of the Docker instructions, so we can keep the biggest amount of data in static unchanging layers. Hang on.

**Comment by blabla1337** [comment]
See my fix based on your work:
https://github.com/blabla1337/skf-labs/commit/2f24eb3d1f49ede7707456de8d794b3b2dfdf0fc

You think we can shrink it more or this is what we get? :)

**Comment by tsluyter** [comment]
Whoa you got it down even further? That's pretty impressive! Of course, what we *should* be careful about is that we should keep as many of the layers between lab machines "shared", because that will also help space savings. If the first few layers of the lab containers are identical, but a bit larger when compared to different-but-smaller layers then the first is preferable.

**Comment by tsluyter** [comment]
Canceling this pull request, because you have implemented these changes through your own branches.

**Pull request closed without merging**
